### ISSUE TITLE
EVTX Attack Samples

### ISSUE THREAD

**Issue by who1smrrobot** [who1smrrobot/DetectionLab#2]
nano ESXi/ansible/roles/wef/tasks/main.yml

Modify EVTX sampels to ELK stack and not to splunk

```
- name: Installing the EVTX Event Samples
  win_shell: ".\\install-evtx-attack-samples.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: evtxeventsamples
  failed_when: "'Exception' in evtxeventsamples.stdout"
```
